name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js version 18 (or the version you prefer)
          cache: 'npm'      # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm ci         # Use `npm ci` for clean, reproducible installations
        # Alternatively, you can use `npm install --prefer-offline`

      - name: Run Linter
        run: npm run lint

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
